name:                JellyVM
version:             0.1.0.0
github:              "mesabloo/jellyvm"
license:             GPL-3.0
author:              "Mesabloo"
copyright:           "2019 Mesabloo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Mesabloo/JellyVM#readme>

dependencies:
- base >= 4.7 && < 5
- criterion-measurement

library:
  source-dirs: src
  ghc-options:
  - -O6

executables:
  JellyVM-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O6
    dependencies:
    - JellyVM
